### ISSUE TITLE
Todo Owus 3

### ISSUE THREAD

**Issue by mininao** [club-vacances/owus#1]
Features de base : 
- [ ] Liste des dettes/prêts
- [ ] Historique des transactions avec un utilisateur
- [ ] Historique de toutes les transactions ( + tri dettes/prêts )
- [ ] Créer une dépense (Qui paie/ Pour qui/ Quoi/ Combien)
- [ ] Remboursement
- [ ] Edit transaction
- [ ] Dans la sélection du pour qui : soi en haut, tri par frecency, quick select avec les photos
- [ ] Login Facebook
- [ ] Somme des Dettes/Prêts

Nouvelles features : 
- [ ] Quoi d'une nouvelle transaction pré-rempli (Selon le jour/l'heure/localisation)
- [ ] Make user suggestions smarter
- [ ] Prettier / More useful landing page for disconnected users
- [ ] Notifications (to be defined)
- [ ] Add debt with anonymous (text)
- [ ] Send a reminder (Auto/Manuel)
- [ ] Groupes d'amis
- [ ] Simplification des remboursements au sein d'un groupe
- [ ] Suggestion de création de groupes
- [ ] Login Twitter/Instagram (plutôt pas, pas tes amis)
- [ ] Reboursement avec paypal/lydia
- [ ] Landing Page
- [ ] Notifications de transaction avec possibilité d'invalider
- [ ] QR Code / String pour ajouter des gens pas dans le répertoire facebook
- [ ] Régler les problèmes de nombres à virgule
- [ ] 
- [ ]
