### ISSUE TITLE
Todo Owus 2

### ISSUE THREAD

**Issue by mininao** [club-vacances/owus#4]
Done :
- [x]  Fix pictures
- [x] Display only if > 0
- [x] Filter cleared when user selected
- [x] Picture of payer in expense timeline
- [x] Improve user picker with user suggestions
- [x] Handle overflow-x in suggestions
- [x] Bug firefox
- [x] Don't automatically reconnect after disconnecting
- [x] Resize sidebar on desktop
- [x] Double column debts view on desktop
- [x] Load web font over https
- [x] Add loading animation when waiting for api
- [x] Pluralization "dépense(s)"
- [x] Debts total (top right corner of card) and/or global balance ?
